services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      DOCKER_STEPCA_INIT_NAME: ${DOCKER_STEPCA_INIT_NAME}
      DOCKER_STEPCA_INIT_DNS_NAMES: ${DOCKER_STEPCA_INIT_DNS_NAMES}
      DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: ${DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT}
      DOCKER_STEPCA_INIT_ACME: ${DOCKER_STEPCA_INIT_ACME}
      STEP_CA_PASSWORD: ${STEP_CA_PASSWORD}
    volumes:
      - /data/step-ca:/home/step
    networks:
      homelab:
        aliases:
          - step-ca.test
    logging:
      driver: json-file
      options:
        max-size: 1M
        max-file: "2"

networks:
  homelab:
    name: homelab
    driver: bridge
